# Generated by Django 4.2.11 on 2024-03-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("core", "0002_property_created_at_property_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="properties.property"
            ),
        ),
        migrations.DeleteModel(
            name="Property",
        ),
    ]
