# Generated by Django 4.2.11 on 2024-03-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_booking_property_alter_pricingrule_property_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PricingRule",
        ),
    ]
