# Generated by Django 4.2.11 on 2024-03-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_pricingrule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
