# Generated by Django 4.2.11 on 2024-03-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="stay_length",
            field=models.IntegerField(null=True),
        ),
    ]
