# Generated by Django 4.2.11 on 2024-03-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_stay_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="date_end",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="date_start",
            new_name="start_date",
        ),
    ]
